# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: gradle/wrapper-validation-action@v1.0.4

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '17' ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - name: Upload artifacts
        if: matrix.java == '8'
        uses: actions/upload-artifact@v2
        with:
          name: JAR artifacts
          path: |
            client/build/libs
            server/build/libs
